SPACESHIP_AWS_PREFIX="using "
SPACESHIP_AWS_SUFFIX=" "
SPACESHIP_AWS_SYMBOL="☁️  "

SPACESHIP_VENV_PREFIX="using "
SPACESHIP_VENV_SYMBOL="🐍 "
SPACESHIP_VENV_COLOR="yellow"

SPACESHIP_TERRAFORM_SHOW=true


SPACESHIP_DIR_TRUNC_REPO=true