SPACESHIP_AWS_PREFIX="using "
SPACESHIP_AWS_SYMOBL="☁️"

SPACESHIP_VENV_PREFIX="using "
SPACESHIP_VENV_SYMBOL=" "
SPACESHIP_VENV_COLOR="226"

SPACESHIP_TERRAFORM_SHOW=true
SPACESHIP_TERRAFORM_ASYNC=false
SPACESHIP_TERRAFORM_SYMBOL="󱁢 "
SPACESHIP_TERRAFORM_COLOR="129"

SPACESHIP_GIT_SHOW=true
SPACESHIP_DIR_TRUNC_REPO=true